# Site settings
title: 
header-img: img/home-bg.png
email: michael.4486@gmail.com
copyright_name: bc86
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  bc86
learn_profile: bc86
email_username: michael.4486@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
